# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore src/BookStoreApi.sln

    - name: Build
      run: dotnet build --no-restore src/BookStoreApi.sln --configuration Release

    - name: Unit tests
      run: dotnet test --no-build src/BookStoreApi.sln --no-restore --configuration Release --filter FullyQualifiedName!~IntegrationTests

    - name: Integration tests
      run: dotnet test --no-build src/BookStoreApi.sln --no-restore --configuration Release --filter FullyQualifiedName~IntegrationTests

    - name: Publish
      run: dotnet publish src/BookStoreApi.sln --configuration Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dianper-bookstoreapi'
          slot-name: 'production'
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_eb2ea8e568304f7391e3ed4b80432d88 }}
